apiVersion: v1
kind: Service
metadata:
  name: utloadbalancerservice
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-size-unit: "1"
    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
spec:
  type: LoadBalancer
  selector:
    app: utbuild
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080



# apiVersion: v1
# kind: Service
# metadata:
#   name: load-balancer-3
#   annotations:
#     service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
#     service.beta.kubernetes.io/do-loadbalancer-size-unit: "3"
#     service.beta.kubernetes.io/do-loadbalancer-algorithm: "round_robin"
#     service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
# spec:
#   type: LoadBalancer
#   externalTrafficPolicy: Local
#   selector:
#     app: utbuild
#   ports:
#     - name: http
#       protocol: TCP
#       port: 80
#       targetPort: 80
#     - name: https
#       protocol: TCP
#       port: 443
#       targetPort: 80

# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: utbuild
#   annotations:
#     nginx.ingress.kubernetes.io/use-regex: "true"
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /api
#         backend:
#           serviceName: utbuild
#           servicePort: 80